### ISSUE TITLE
Qdyn6 stuck when using polarisation restraints

### ISSUE THREAD

**Issue by Pyshou** [qusers/Q6#10]
Hi guys,

I recently decided to switch from Q5 to version 6 and compiled it using intel 17.0 and intel mpi 2017. Everything works fine except that Qdyn6 gets stuck whenever it reaches the printed "Nonbonded pair list generation" section. This happens whenever solvent polarisation restraints are turned on.

Any idea if there is something to fix somewhere in the code? I compiled it exactly the same way as David did, on the same supercomputer cluster. But I am probably using a version that has been slightly updated on GitHub. I will let you know if I figure that out. PS: I tired that on several systems that worked well with Q5.

Cheers!

Pierre

**Comment by Pyshou** [comment]
Solved!

**Comment by esguerra** [comment]
Hej Pierre,

Care to share what solved the issue and a little bit more of your case use.
I'm sure everyone will benefit who might come across with the same issue.

Thanks,

Mauricio

**Comment by Pyshou** [comment]
Hej Mauricio!

Sorry, I was still trying to understand this further. Now I got it. I am not using Q to solvate my system but I am instead taking and formatting water oxygen atoms from a simulation with another package (then adding hydrogens when generating the topology with Q). In this case, the resulting topology has no value for the "solvent dielectric as eps*1000" (which should be 80100 in my case with TIP3P models). On top of this, I have to add the solvent density there as well (0.0335 in my case). These values were not shown in Q5 topologies and it seems that they used to be assigned automatically.

Pierre

**Comment by acmnpv** [comment]
Hello,

Thanks for the update. Could you still upload the unmodified (failing) and
modified (working) files? Q6 should have chosen default values for the new
variables when reading in the old files, so this is still a bug that needs
fixing.

Cheers

Paul

**Comment by Pyshou** [comment]
Hi Paul,

You're welcome. You will find my input files enclosed for both scenarios (plus the folder where I generate my topology since you probably want to fix something with Qprep6 too). PS: This time, instead of getting stuck when using the wrong topology, Qdyn6 returns a bench of Fortran errors when reaching the "Nonbonded pair list generation" section (I do not recall what might be the difference with yesterday).

Cheers!

Pierre

[inputs.tar.gz](https://github.com/qusers/Q6/files/1691793/inputs.tar.gz)

**Comment by acmnpv** [comment]
ok, I had a look at the files and see why it happened, with the values for density and dielectric set to zero it will obviously fail in some way :)
Will add some checks for values that make sense there, and close the issue again afterwards!

Thanks again for reporting

**Comment by Pyshou** [comment]
Indeed ^_^ (this values used to be hidden and I didn't see the zero values at first glance). Thanks a lot for the active support ;)

**Comment by Pyshou** [comment]
I noticed another related issue and asked David about it. It turns out that he had the same problem. 

When using Q6 to solvate my system (runs for a small compound in water), it adds waters around the sphere edge (a bit beyond too). This was already the case with Q5 but did not cause any problem. However, I end up with Shake failure issues with Qdyn6, unless I clean up all waters outside the sphere edge and change the "solvent radii" accordingly in the topology (or just increasing the "solvent radii" value seems to fix it in most cases). Maybe this could help improve another bug.

Cheers!

Pierre

**Comment by esguerra** [comment]
Hej Piere,

Can you copy the text above and create a new issue with it with a new title like, "boundary solvation issue" or so.

Thanks,

Mauricio

**Comment by Pyshou** [comment]
Hej Mauricio,

Sure, I'll do that now ;)

Cheers,

Pierre

**Comment by acmnpv** [comment]
I added the enhancement label because this should mainly happen with custom topology files, but anyway needs fixing.
