### ISSUE TITLE
Boundary solvation issue with Qprep6?

### ISSUE THREAD

**Issue by Pyshou** [qusers/Q6#12]
Hi,

I noticed another related issue and asked David about it. It turns out that he had the same problem.

When using Q6 to solvate my system (runs for a small compound in water), it adds waters around the sphere edge (a bit beyond too). This was already the case with Q5 but did not cause any problem. However, I end up with Shake failure issues with Qdyn6, unless I clean up all waters outside the sphere edge and change the "solvent radii" accordingly in the topology (or just increasing the "solvent radii" value seems to fix it in most cases). Maybe this could help fix another bug.

Cheers!

Pierre

**Comment by acmnpv** [comment]
Hej again,

Thanks for the new bug report!
Can you also upload a test case here?
I'll look that I take some time this evening to check what causes the
difference between Q5 and Q6.

Cheers

Paul

**Comment by Pyshou** [comment]
Hej,

You will find input files enclosed. There is one folder with a submission script template and the fixed topology and another with the original one. For fixing it, I used a dirty cleanup_waters.py script that you will find there, to cleanup the generated topology.pdb file with waters around the sphere edge. I then re-run Qprep6 on the generated output using the qprep_noaddwat.in input file not to solvate again (you will find it there), and change the solvent radii, density and dielectric*1000 in the topology accordingly (as pointed out with the previous issue that occurs when not using "solvate"). Note that with the unfixed topology, I have hot atoms from eq0 step and the Shake failure typically occurs during the next one (eq1, step 5218 for me), when I start to use Shake.

Cheers

Pierre

[inputs.tar.gz](https://github.com/qusers/Q6/files/1696178/inputs.tar.gz)

**Comment by acmnpv** [comment]
Hej, I'm sorry but I think I this is not a bug in the new version (and the old version is incorrect in running your stuff). Your original topology has errors in it, so anything that came from it is suspect. Also, analysing your energies shows that is not the polarization forces that are acting up initially, but the Q-Q vdW, indicating other issues in the original run. The polarization only comes up later when the system has already blown up :)

Topology error is this:
>>>>> ERROR: Inconsistent molecule/residue start atoms 

Please fix your topology and then test again if this issue persists.

**Comment by Pyshou** [comment]
Hi Paul,

Thanks again and sorry for the spamming :). Actually, I was using generated ff parameters for small compounds from LigParGen's web server and it turns out that there was an extra column in the impropers section of the .prm file (leading to a wrong topology with wrong equilibrium angle values). In addition, some extra lines (header, CONNECT records..) in the input structure file had to be removed. Otherwise, there is no problem with the boundary solvation features (we just need to set our custom solute density to get the solvent radius right in the case of receptor-membrane-ligand systems or set it by hand as we are using old waters and not solvating).

Cheers!

Pierre

**Comment by esguerra** [comment]
Hej Pierre,

Thanks for reporting back.
It helps everyone to know. 

Cheers, 

M.

**Comment by mpurg** [comment]
Hi Pierre,

Don't want to spam this thread, but thought I'd give a heads up.
LigParGen gives wrong torsional/improper parameters for Q. Force constants
are all x2.

I attached Phenol parameters produced via LigParGen and via
ffld_server/qtools.
The latter agree with Tyr parameters in the standard library.

Cheers,
Miha

2018-02-13 18:26 GMT+01:00 Pierre Matricon <notifications@github.com>:

**Comment by Pyshou** [comment]
Hi Miha,

Thanks for the notice. I will considering that too (we've seen this recently).

Cheers!

Pierre

**Comment by acmnpv** [comment]
Can this be closed then?

**Comment by Pyshou** [comment]
Sure!
