### ISSUE TITLE
qdyn6 gives incorrect error message

### ISSUE THREAD

**Issue by dblahanelson** [qusers/Q6#6]
Running qdyn6 without a fep files gives the error that the [atoms] section is missing from the fep file. It should say that it doesn't have a fep file at all.

**Comment by kamerlin** [comment]
That is basically what it is saying. It is fine as is.

⁣Sent from BlueMail ​

**Comment by acmnpv** [comment]
I agree that the error message could state things more obviously, but this is not a pressing thing to fix :)
If someone wants to work on this I'll of course have a look at it, but closing this for now
