### ISSUE TITLE
Qprep6 fortran error when averaging dcds to pdb

### ISSUE THREAD

**Issue by dblahanelson** [qusers/Q6#8]
Using qprep6 on triolith to average a dcd into a pdb. Log file gives error ">>>>> ERROR: invalid coordinate array size." and a long fortran error beginning:

"*** glibc detected *** /home/x_davbl/qsource/Q6/bin/Qprep6: double free or corruption (!prev): 0x00000000023077f0 ***"

It does produce an output pdb, but I can't say if it's correct or not.
[qprep6_error.zip](https://github.com/qusers/Q6/files/1677056/qprep6_error.zip)

**Comment by dblahanelson** [comment]
I can now also confirm that the pdb produced is simply the same coordinates as the topology file; it is not an averaged structure of the dcd.

**Comment by acmnpv** [comment]
ok, I can reproduce it locally, seems to be an error when checking the size of the atom masks

**Comment by acmnpv** [comment]
Mauricio, can you check the fixed commit again? I uploaded it over the old one (sorry about that).
The calculation should now reproduce results from your reference version.

Cheers!

**Comment by esguerra** [comment]
Hej,
Looking into it.
Just cloned the bugfix branch a second ago to take a look.
Cheers,
M.
